spring.application.name=rent.manager

#DATABASE SETUP
spring.datasource.url=${TANTE_DB_URL}
spring.datasource.username=${TANTE_DB_USERNAME}
spring.datasource.password=${TANTE_DB_PASSWORD}

# JPA / Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8080
server.address=0.0.0.0


# CORS CONFIG
app.cors.allowed-origins=http://localhost:4173,http://192.168.1.81:4173,https://letsexploretanzania.com,https://admin.letsexploretanzania.com,http://169.254.17.29:4173
app.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
app.cors.allowed-headers=Authorization,Content-Type,Accept,Origin
app.cors.exposed-headers=Authorization
app.cors.allow-credentials=true
